theme: "hugo-PaperMod"
baseURL: /
languageCode: en-us
title: Home
publishDir: docs
ignoreFiles: 
      - \.Rmd$
      - \.Rmarkdown$
      - _cache$
      - \.knit\.md$
      - \.utf8\.md$
publishdir: tocs
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
menu:
    main:
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 10  
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 30
        - identifier: Search
          name: search
          url: /search/
          weight: 40
params:
    label:
        icon: /img/logo.png
        iconHeight: 35
    env: production
    ShowBreadCrumbs: true
    description: Luo Fei's web site
    homeInfoParams:
        Title: Luo Fei Site
        Content: >
            Welcome to My blog：
            
            - 🧔 I am a public health reasearcher worked in Chongqing China.
            
            - 💻 I am learing using R language  for statistical analysis in infectious diseses. 
            
            - 🎡 I will record the issues in the learning process and my own solutions here, and I will also record my daily life . 
            You are welcome to leave your valuable comments
            
            - 😜 Many thanks for you visting  ! 
    socialIcons:
        - name: Github
          url: https://github.com/luofeicq/
        - name: Zhihu
          url: https://www.zhihu.com/people/tai-gu-mao    

assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
analytics:
         google:
             SiteVerificationTag: "G-FTJY4N1GXR"    
markup:
  goldmark:
    renderer:
      unsafe: true
