theme: "hugo-PaperMod"
baseURL: /
languageCode: zh-cn
title: Home
publishDir: docs
relativeurls: true
ignoreFiles: 
      - \.Rmd$
      - \.Rmarkdown$
      - _cache$
      - \.knit\.md$
      - \.utf8\.md$
      - _bookdown
publishdir: tocs
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
menu:
    main:
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 10  
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 30
        - identifier: Search
          name: search
          url: /search/
          weight: 40
params:
    #math: true
    assets:
        disableHLJS: false
    utteranc:
        enable: true
        repo: luofeicq/luofeiblog
        issueTerm: BlogComments
        theme: github-light
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableScrollToTop: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false
    fancybox: true
    label:
        icon: /img/logo.png
        iconHeight: 35
    env: production
    description: Luo Fei's web site
    homeInfoParams:
        Title: Luo Fei Site
        Content: >
            Welcome to My blog：
            
            -  I am a public health reasearcher worked in Chongqing China.
            
            -  I am learing using R language  for statistical analysis in infectious diseses. 
            
            -  I will record the issues encountered during the learning process as well as my solutions. 
            You are welcome to leave your valuable comments
            
            -  Many thanks for your visting  ! 
    socialIcons:
        - name: Github
          url: https://github.com/luofeicq/
        - name: Zhihu
          url: https://www.zhihu.com/people/tai-gu-mao
analytics:
         google:
             SiteVerificationTag: "G-FTJY4N1GXR"    
markup:
    goldmark:
        renderer:
            unsafe: true
