---
title: ggplot2笔记
author: Luo Fei
date: '2022-04-08'
slug: ggplot2_note
categories:
  - 中文
  - Tec
tags:
  - R
output:
    blogdown::html_page:
        number_sections: true
math: true
showToc: true
TocOpen: false
toc-title: "目录"
draft: false
hidemeta: false
comments: false
description: "无责任猜测。"
canonicalURL: ""
disableShare: false
hideSummary: false
searchHidden: false
ShowReadingTime: false
ShowBreadCrumbs: true
ShowPostNavLinks: true
cover:
    image: "" # image path/url
    alt: "<alt text>" # alt text
    caption: "<text>" # display caption under cover
    relative: false # when using page bundles set this to true
    hidden: true # only hide on current single page    
---

```{r,setup,include=FALSE}
options(digits = 2)

##knitr设置
knitr::opts_chunk$set(
  prompt = FALSE,
  comment = "#",
  results = "markup",
  error = FALSE,
  message = FALSE,
  fig.align = "center",
  collapse = FALSE,
  tidy = F,
  echo = F,
  message = F,
  results = "hide",
  warning = F
  )

```

使用到的R包：

```{r}
library(tidyverse)
library(ggforce)
library(ggthemes)
library(gghighlight)
library(readxl)
library(openxlsx)
```

# gghigglight包的使用

```{r}

test <- read_excel("data/covidlj.xlsx")
test %>% select_if(
  ~any(!is.na(.))
) %>% mutate(
  across(is.numeric, ~ replace_na(., 0))
) %>% select(c(-1,-3))

```

```{r}
lines <- data.frame(
  x = c(5, 12, 15, 9, 6),
  y = c(17, 20, 4, 15, 5),
  xend = c(19, 17, 2, 9, 5),
  yend = c(10, 18, 7, 12, 1),
  width = c(1, 10, 6, 2, 3),
  colour = letters[1:5]
)
ggplot(lines) +
  geom_link(aes(x = x, y = y, xend = xend, yend = yend, colour = colour,
                alpha = stat(index), size = stat(index)))
ggplot(lines) +
  geom_link2(aes(x = x, y = y, colour = colour, size = width, group = 1),
             lineend = 'round', n = 500)

ggplot(lines) +
  geom_link0(aes(x = x, y = y, xend = xend, yend = yend, colour = colour))
```

